### ISSUE TITLE
Logger Module

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/ratchet-server#1]
Logs should be in format

DATETIMESTAMP [LOGTYPE] (LOCATION) FUNCTION(): MESSAGE

EXAMPLE:
01/25/2015 13:05:01 [Warning] (GameObject) GameObject::Init(): No default value specified

LOGTYPE can be one of the following:
Critical - non recoverable
Error - recoverable
Warning
Info - most actions

There should also be an option to only print certain LOGTYPEs
There should be an option to specify a logfile and if the user wants to log to that file or on screen or both.

**Comment by AdamHarter** [comment]
For function names __PRETTY_FUNCTION__ works on GCC and __FUNCDNAME__ works on MSVC, could define a macro (such as FUNC_NAME) that automatically sets it based off the compiler.

**Comment by russleyshaw** [comment]
I'd stay away from anything that isnt considered standard.

If it is, then go for it.

**Comment by russleyshaw** [comment]
The main hope is that 99% of the code is crystal clear and doesnt make us scratch our heads and go "what"

**Comment by AdamHarter** [comment]
__func__ is standard, but (I believe) is subject to C++'s name mangling.
Also if no log file is specified does it default to std::cerr?  A static file?  Or some sort of log{date} file?

**Comment by russleyshaw** [comment]
outputs to stdout unless flag is given, then written to file.

there should also be a compiler flag to basically remove the logging alltogether.

**Comment by russleyshaw** [comment]
Organization between err, warnings can be done via GREP

**Comment by AdamHarter** [comment]
Are we going to use Boost?
If so http://www.boost.org/doc/libs/1_57_0/libs/log/doc/html/index.html
Also for header files are we doing .h or .hpp?

**Comment by russleyshaw** [comment]
I was hoping to use C++11 stuff as much as possible and only use boost if necessary. I think we can get away with STL for C++11 for everything (if not, most).

I was taught to use .h for normal .cpp files and .hpp for templates.

Which is considered to be "right and modern"?

**Comment by AdamHarter** [comment]
It's up to preference, such as using .cpp or .cxx
In Boost they use .hpp because it is unambiguously a C++ header, while a .h can be either C++ or C.
Also Boost logger is kind of overkill for this, so it makes sense to just make one.

**Comment by russleyshaw** [comment]
Let's use .h since whenever I see .hpp, I think template.

**Comment by russleyshaw** [comment]
Logger is pretty important actually since you cant really step through line by line in a multiprocess application.

**Comment by russleyshaw** [comment]
Parallel to .h vs .hpp

I believe we should follow the Google C++ style guide as much as possible.

http://google-styleguide.googlecode.com/svn/trunk/cppguide.html

It says .cc for C++ files and .h for headers
