### ISSUE TITLE
Communication.

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/ratchet-server#4]
We need an easier way to communicate...

Any ideas?

**Comment by AdamHarter** [comment]
siggame.slack.com
I don't think there's a group for new framework/whatever discussion but you can get one made, I'm sure.

**Comment by russleyshaw** [comment]
Trey doesnt wanna let me in because of game specific info.
I'll ask wisely if he can set up some sort of permissions.

**Comment by russleyshaw** [comment]
http://ratchetframework.stack.com for future reference
